version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app   # Mapear a pasta 'app' local para o diretório /app no container
    ports:
      - "8000:8000"
    command: python /app/manage.py runserver 0.0.0.0:8000
